[package]
name = "bri-motor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
bri-content = { path = "../content" }
bri-physics = { path = "../physics" }
glam = { version = "0.33", features = ["serde"] }
rapier3d = { version = "=0.36.0", features = ["enhanced-determinism"] }
