[package]
name = "bri-weapons"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
publish = false
[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
glam = { workspace = true, features = ["serde"] }
bri-content = { path = "../content", version = "0.1.0" }
bri-package = { path = "../package" }
[dev-dependencies]
rapier3d.workspace = true
bri-physics = { path = "../physics", version = "0.1.0" }
