[package]
name = "bri-render"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bri-content = { path = "../content" }
serde.workspace = true
anyhow.workspace = true
serde_json.workspace = true
sha2.workspace = true
pollster.workspace = true
png.workspace = true
image = { workspace = true, features = ["jpeg"] }
bytemuck.workspace = true
glam.workspace = true
wgpu.workspace = true

[dev-dependencies]
bri-package = { path = "../package" }
