[package]
name = "bri-fx-runtime"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
publish = false


[dependencies]
bri-render = { path = "../render" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
glam.workspace = true
bytemuck.workspace = true
image = { workspace = true, features = ["jpeg"] }
wgpu.workspace = true
bri-content = { path = "../content" }
rayon = "1.12"

[dev-dependencies]
pollster.workspace = true
