#!/usr/bin/env python3
"""Render extracted GUI trees (from gui_extract.py) into per-GUI Markdown
outlines with source line numbers and absolute rects at the authored 640x480
reference resolution. Absolute rects ignore horiz/vertSizing resize rules,
which the engine applies when the canvas is larger (see engine-behavior doc).

Usage: gui_outline.py data/v20-static-objects.json data/gui-layouts
"""
import json, sys, os

SRC = '.research/v20-dso/client/ui/allClientGuis-Vanilla.gui'
KEYS = ['text', 'bitmap', 'command', 'altCommand', 'accelerator', 'variable',
        'buttonType', 'groupNum', 'closeCommand', 'mColor', 'color', 'value',
        'range', 'ticks', 'maxLength', 'wrap', 'noCursor', 'tooltip']

def pair(v, default=(0, 0)):
    try:
        a = [int(float(x)) for x in str(v).split()]
        return (a[0], a[1])
    except Exception:
        return default

def fmt(v):
    if isinstance(v, dict):
        return '`' + v['expr'] + '`'
    s = str(v).replace('\n', '\\n').replace('|', '\\|')
    if len(s) > 90: s = s[:87] + '...'
    return '"' + s + '"'

def walk(o, ox, oy, depth, out):
    f = o['fields']
    px, py = pair(f.get('position', '0 0'))
    ex, ey = pair(f.get('extent', '0 0'))
    ax, ay = ox + px, oy + py
    name = o['name'] or ''
    parts = [f"L{o['line']}", f"**{o['class']}**" + (f"(`{name}`)" if name else '')]
    parts.append(f"rel {px},{py} ext {ex}x{ey} abs {ax},{ay}")
    if 'profile' in f: parts.append('profile=' + str(f['profile']))
    hs, vs = f.get('horizSizing'), f.get('vertSizing')
    if hs and vs and (hs, vs) != ('right', 'bottom'): parts.append(f'sizing={hs}/{vs}')
    if f.get('visible') == 0: parts.append('HIDDEN')
    for k in KEYS:
        if k not in f:
            continue
        v = f[k]
        # keep literal 0 for text/accelerator (decompiler emits `text = 0;` for "0")
        if v == '' or (v == 0 and k not in ('text', 'accelerator', 'value')):
            continue
        parts.append(f'{k}={fmt(v)}')
    out.append('  ' * depth + '- ' + ' · '.join(parts))
    for c in o['children']:
        walk(c, ax, ay, depth + 1, out)

def main(src, outdir):
    d = json.load(open(src))
    guis = d['allClientGuis-Vanilla.gui']
    os.makedirs(outdir, exist_ok=True)
    index = ['# Generated v20 GUI layout outlines', '',
             f'Source: `{SRC}` (decompiled from Maxwell\'s installed allClientGuis-Vanilla.gui.dso;',
             'byte-identical to upstream bl-decompiled/v20 after CRLF normalisation).',
             'Generated by `tools/gui_outline.py`; do not hand-edit. `L<n>` = source line.', '',
             '| GUI | Class | Line | Controls |', '|---|---|---:|---:|']
    for o in guis:
        def cnt(x): return 1 + sum(cnt(c) for c in x['children'])
        nm = o['name'] or f"anon_{o['line']}"
        if o['class'] == 'GuiControlProfile':
            index.append(f"| {nm} | profile | {o['line']} | - |"); continue
        out = [f'# {nm}', '', f"`{SRC}` lines {o['line']}–{o.get('end_line')}", '']
        walk(o, 0, 0, 0, out)
        with open(os.path.join(outdir, nm + '.md'), 'w') as fh:
            fh.write('\n'.join(out) + '\n')
        index.append(f"| [{nm}]({nm}.md) | {o['class']} | {o['line']} | {cnt(o)} |")
    with open(os.path.join(outdir, 'README.md'), 'w') as fh:
        fh.write('\n'.join(index) + '\n')

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
