#!/usr/bin/env python3
"""Tabulate GuiControlProfile definitions (fonts, colors, skins) and how many
static controls use each. Usage: profiles_table.py data/v20-static-objects.json out.md"""
import json, sys
from collections import Counter
d = json.load(open(sys.argv[1]))
profiles, uses = {}, Counter()
def walk(o, f):
    if o['class'] == 'GuiControlProfile':
        profiles[o['name']] = (o, f)
    elif 'profile' in o['fields']:
        uses[str(o['fields']['profile'])] += 1
    for c in o['children']:
        walk(c, f)
for f, objs in d.items():
    for o in objs:
        walk(o, f)
COLS = ['fontType', 'fontSize', 'fontColor', 'fontColorHL', 'fontColors[0]', 'fillColor', 'opaque', 'border',
        'bitmap', 'hasBitmapArray', 'justify', 'textOffset', 'doFontOutline', 'fontOutlineColor', 'modal', 'canKeyFocus']
out = ['# Generated GUI profile table', '',
       'Generated by `tools/profiles_table.py`. Profiles are Torque GuiControlProfile objects: they carry the',
       'font, colors and bitmap skin a control renders with. `uses` counts static controls in the vanilla GUI',
       'file that name the profile (dynamic controls created in scripts are not counted). `inherits` is the',
       'parent profile when declared as `Name : Parent`; unspecified fields come from the parent or engine defaults.', '',
       '| Profile | Source line | inherits | uses | ' + ' | '.join(COLS) + ' |',
       '|' + '---|' * (4 + len(COLS))]
for name in sorted(profiles, key=lambda n: (-uses[n], n)):
    o, f = profiles[name]
    fl = o['fields']
    def v(k):
        x = fl.get(k, '')
        if isinstance(x, dict): x = x['expr']
        return str(x).replace('|', '\\|')
    out.append(f"| {name} | {f}:{o['line']} | {o.get('parent','')} | {uses[name]} | " + ' | '.join(v(k) for k in COLS) + ' |')
undefined = sorted(p for p in uses if p not in profiles)
out += ['', '## Profiles used but not defined in these files', '',
        'These must come from engine built-ins or other script files; see engine-behavior notes.', '']
out += [f'- `{p}` — used by {uses[p]} static controls' for p in undefined]
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
print(len(profiles), 'profiles;', len(undefined), 'undefined:', undefined)
