[package]
name = "bri-fx-import"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
publish = false


[dependencies]
anyhow.workspace = true
serde_json.workspace = true
regex.workspace = true
zip.workspace = true
bri-content = { path = "../content" }
bri-fx-runtime = { path = "../fx-runtime" }
