[package]
name = "bri-weapons-import"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
publish = false
[dependencies]
bri-weapons = { path = "../weapons", version = "0.1.0" }
bri-convert = { path = "../convert", version = "0.1.0" }
anyhow.workspace = true
serde_json.workspace = true
regex.workspace = true
sha2.workspace = true
zip.workspace = true
