[package]
name = "bri-identity"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bri-files.workspace = true
anyhow.workspace = true
ring = "0.17.14"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }

[dev-dependencies]
tempfile = "3"
