//! Generated coverage table (Markdown) — always consistent with the pack.

use std::collections::BTreeMap;
use std::fmt::Write;

use bri_audio::schema::{PackManifest, Severity, SoundStatus};

use crate::model::Inventory;

fn yn(b: bool) -> &'static str {
    if b { "yes" } else { "no" }
}

pub fn coverage_markdown(m: &PackManifest, inv: &Inventory) -> String {
    let mut s = String::new();
    let sm = &inv.summary;
    let _ = writeln!(s, "# Vanilla audio coverage — {}\n", m.pack_id);
    let _ = writeln!(
        s,
        "Generated by `{} {}` from the designated reference installation. Do not edit by hand; \
         re-run the converter. Evidence paths are relative to the project root (decompiled scripts) \
         or the reference installation (`Add-Ons/X.zip!member`).\n",
        m.generator.name, m.generator.version
    );
    let _ = writeln!(s, "## Totals\n");
    let _ = writeln!(s, "| Item | Count |\n| --- | ---: |");
    for (k, v) in [
        (
            "Audio files found (loose + archive members)",
            sm.audio_files,
        ),
        ("WAV files", sm.wav_files),
        ("OGG files", sm.ogg_files),
        ("Unique clips (by SHA-256)", sm.unique_clips),
        ("Clips decoded and validated", sm.clips_decoded),
        ("Clips failing to decode", sm.clips_failed),
        ("AudioDescriptions", sm.descriptions),
        ("Static AudioProfiles", sm.profiles_static),
        ("Rule-generated music profiles", sm.profiles_generated_music),
        ("Sounds ready to play", sm.sounds_ready),
        (
            "Sounds unavailable (explicit reason)",
            sm.sounds_unavailable,
        ),
        ("Datablock field bindings", sm.bindings),
        ("Script audio call sites", sm.call_sites),
        ("Engine-bound profiles", sm.engine_bound),
        ("Trigger mappings", sm.triggers),
        (
            "Audio files not named by any profile",
            sm.unreferenced_audio_files,
        ),
    ] {
        let _ = writeln!(s, "| {k} | {v} |");
    }
    let _ = writeln!(s);

    let mut fam: BTreeMap<&str, (usize, usize, usize)> = BTreeMap::new();
    for snd in &m.sounds {
        let e = fam.entry(snd.family.as_str()).or_default();
        e.0 += 1;
        if snd.is_ready() {
            e.1 += 1;
        }
        if snd.default_enabled {
            e.2 += 1;
        }
    }
    let _ = writeln!(
        s,
        "## By family\n\n| Family | Sounds | Ready | In default-enabled packages |\n| --- | ---: | ---: | ---: |"
    );
    for (f, (n, r, d)) in &fam {
        let _ = writeln!(s, "| {f} | {n} | {r} | {d} |");
    }
    let _ = writeln!(s);

    let _ = writeln!(
        s,
        "## Sounds\n\n\
         Gain is the description volume; distances are world units (Torque linear rolloff: full inside ref, silent at max). \
         `ch` is the vanilla channel (1 shell/interface, 2 sim/effects). `Triggers` counts trigger-table rows.\n"
    );
    let _ = writeln!(
        s,
        "| Sound id | Datablock | Package | Family | Status | Gain | Loop | 3D ref/max | ch | Bus | Triggers | Lists | Defined at |"
    );
    let _ = writeln!(
        s,
        "| --- | --- | --- | --- | --- | ---: | --- | --- | ---: | --- | ---: | --- | --- |"
    );
    for snd in &m.sounds {
        let status = match &snd.status {
            SoundStatus::Ready => "ready".to_string(),
            SoundStatus::MissingClip { requested, .. } => format!("MISSING `{requested}`"),
            SoundStatus::MissingDescription { requested } => {
                format!("no description `{requested}`")
            }
            SoundStatus::Undecodable { file } => format!("UNDECODABLE `{file}`"),
            SoundStatus::RejectedByVanilla { reason } => format!("rejected: {reason}"),
        };
        let p = &snd.playback;
        let spatial = p
            .spatial
            .map(|sp| format!("{}/{}", sp.reference_distance, sp.max_distance))
            .unwrap_or_else(|| "2D".into());
        let triggers = m.triggers.iter().filter(|t| t.sound == snd.id).count();
        let _ = writeln!(
            s,
            "| `{}` | {} | {}{} | {} | {} | {} | {} | {} | {} | {:?} | {} | {} | {}:{} |",
            snd.id,
            snd.name,
            snd.package,
            if snd.default_enabled {
                ""
            } else {
                " (off by default)"
            },
            snd.family,
            status,
            p.gain,
            yn(p.looping),
            spatial,
            p.channel,
            p.bus,
            triggers,
            snd.lists.join(", "),
            snd.defined_at.file,
            snd.defined_at.line
        );
    }
    let _ = writeln!(s);

    let _ = writeln!(s, "## Music rule\n\n{}\n", inv.music_rule.rule);
    let _ = writeln!(
        s,
        "| File | Datablock | Flag | Bytes | Channels | Accepted | Reason |\n| --- | --- | --- | ---: | ---: | --- | --- |"
    );
    for c in &inv.music_rule.candidates {
        let _ = writeln!(
            s,
            "| {} | {} | {} | {} | {} | {} | {} |",
            c.file,
            c.datablock,
            c.flag.clone().unwrap_or_else(|| "-".into()),
            c.bytes,
            c.channels
                .map(|v| v.to_string())
                .unwrap_or_else(|| "?".into()),
            yn(c.accepted),
            c.reason.clone().unwrap_or_default()
        );
    }
    let _ = writeln!(s);

    let _ = writeln!(s, "## Audio files not named by any profile\n");
    for f in inv
        .audio_files
        .iter()
        .filter(|f| f.referenced_by.is_empty())
    {
        let _ = writeln!(
            s,
            "- `{}` ({}), preserved as `{}`",
            f.virtual_path, f.package, f.clip
        );
    }
    let _ = writeln!(s);

    let _ = writeln!(
        s,
        "## Trigger map\n\nSemantic keys (e.g. `player.jump`) are curated for direct use; `datablock:`, `call:`, \
         `engine:` and `music-brick:` keys are generated from every binding/call site so nothing authored is lost. \
         Placement: `listener` = 2D, `world` = fixed position, `attached` = follows the emitting object.\n"
    );
    let _ = writeln!(
        s,
        "| Key | Sound | Placement | Source | When | Evidence |\n| --- | --- | --- | --- | --- | --- |"
    );
    for t in &m.triggers {
        let ev: Vec<String> = t
            .evidence
            .iter()
            .take(3)
            .map(|e| format!("{}:{}", e.file, e.line))
            .collect();
        let more = if t.evidence.len() > 3 {
            format!(" (+{})", t.evidence.len() - 3)
        } else {
            String::new()
        };
        let _ = writeln!(
            s,
            "| `{}` | `{}` | {:?} | {} | {}{} | {}{} |",
            t.key,
            t.sound,
            t.placement,
            t.source,
            t.label.replace('|', "/"),
            t.note
                .as_ref()
                .map(|n| format!(" — {n}"))
                .unwrap_or_default(),
            ev.join("; "),
            more
        );
    }
    let _ = writeln!(s);

    let _ = writeln!(s, "## Errors and warnings\n");
    for d in m
        .diagnostics
        .iter()
        .filter(|d| d.severity >= Severity::Warning)
    {
        let ev: Vec<String> = d
            .evidence
            .iter()
            .map(|e| format!("{}:{}", e.file, e.line))
            .collect();
        let _ = writeln!(
            s,
            "- **{:?}** `{}` — {} {}",
            d.severity,
            d.code,
            d.message,
            if ev.is_empty() {
                String::new()
            } else {
                format!("({})", ev.join("; "))
            }
        );
    }
    let info = m
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Info)
        .count();
    let _ = writeln!(
        s,
        "\n{info} informational diagnostics (duplicates, unbound profiles, unreferenced files, filename case) are listed in `manifest.json`."
    );
    s
}
