[package]
name = "bri-world"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bri-files.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["float_roundtrip"] }
glam = "0.33"
bri-events = { path = "../events" }

