[package]
name = "bri-foliage"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
publish = false
[dependencies]
anyhow.workspace = true
bri-render = { path = "../render" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
glam = { workspace = true, features = ["serde"] }
bytemuck.workspace = true
image.workspace = true
wgpu.workspace = true
[dev-dependencies]
bri-package = { path = "../package" }
bri-content = { path = "../content" }
pollster.workspace = true
bri-physics = { path = "../physics" }
rapier3d.workspace = true
