"""Offline citation inventory. Reads recovered sources; never executes Torque."""
import hashlib
import json
import pathlib
import re
import argparse

ROOT = pathlib.Path(__file__).resolve().parents[3]
FILES = {
    'server': '.research/v20-dso/server/mainServer.cs',
    'game': '.research/v20-dso/server/scripts/allGameScripts-Vanilla.cs',
    'client': '.research/v20-dso/client/scripts/allClientScripts-Vanilla.cs',
    'gui': '.research/v20-dso/client/ui/allClientGuis-Vanilla.gui',
    'defaults': '.research/bl-decompiled/v20/server/defaults.cs',
}
report = {'schema_version': 1, 'sources': {}, 'role_references': [], 'gui_roots': []}
parser = argparse.ArgumentParser()
parser.add_argument('--reference', type=pathlib.Path,
                    default=pathlib.Path('E:/Downloads/B4v21Launcher/versions/Blockland v20'))
args = parser.parse_args()
for key, relative in FILES.items():
    path = ROOT / relative
    data = path.read_bytes()
    text = data.decode('utf-8-sig')
    report['sources'][key] = {'file': relative, 'sha256': hashlib.sha256(data).hexdigest()}
    dso = path.with_suffix(path.suffix + '.dso')
    if dso.exists():
        report['sources'][key]['dso_sha256'] = hashlib.sha256(dso.read_bytes()).hexdigest()
        suffix = relative.split('/v20-dso/', 1)[1] + '.dso'
        original = args.reference / 'base' / suffix
        original_hash = hashlib.sha256(original.read_bytes()).hexdigest()
        report['sources'][key]['reference_file'] = str(original)
        report['sources'][key]['reference_sha256'] = original_hash
        if original_hash != report['sources'][key]['dso_sha256']:
            raise ValueError(f'Reference DSO differs: {original}')
    elif key == 'defaults':
        original = args.reference / 'base/server/defaults.cs'
        report['sources'][key]['reference_file'] = str(original)
        report['sources'][key]['reference_sha256'] = hashlib.sha256(original.read_bytes()).hexdigest()
        report['sources'][key]['note'] = 'Loose reference defaults are B4v21-modified. Recovered v20 defaults are used, per the vanilla scope contract.'
    functions = list(re.finditer(r'^function\s+([\w:]+)\(', text, re.M)) if key != 'gui' else []
    for index, function in enumerate(functions):
        end = functions[index + 1].start() if index + 1 < len(functions) else len(text)
        body = text[function.start():end]
        if re.search(r'isAdmin|isSuperAdmin|[Aa]utoAdmin|[Aa]utoSuperAdmin|[Aa]dmin[Pp]assword', body):
            report['role_references'].append({
                'source': key, 'function': function[1],
                'line': text.count('\n', 0, function.start()) + 1,
                'end_line': text.count('\n', 0, end),
                'role_test_lines': [text.count('\n', 0, function.start() + m.start()) + 1
                                    for m in re.finditer(r'isAdmin|isSuperAdmin', body)],
            })
    if key == 'gui':
        for m in re.finditer(r'^new GuiControl\(([^)]+)\)', text, re.M):
            if re.search(r'admin|ban|brickman|serverconfig|changemap', m[1], re.I):
                report['gui_roots'].append({'name': m[1], 'line': text.count('\n', 0, m.start()) + 1})
out = ROOT / 'docs/research/admin'
(out / 'evidence.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
lines = ['# Recovered role-reference index', '',
         'Generated by `audit_sources.py`. A role reference is not necessarily an entry permission guard.', '',
         '| Source | Function | Start | End | Role tests |', '| --- | --- | ---: | ---: | --- |']
for entry in report['role_references']:
    lines.append('| {source} | `{function}` | {line} | {end_line} | {tests} |'.format(
        **entry, tests=', '.join(map(str, entry['role_test_lines']))))
(out / 'source-index.txt').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f"Verified {len(report['sources'])} sources, indexed {len(report['role_references'])} role-reference functions")
